import { useMemo, useState } from "react";
import { ArrowRight, Check, ChevronDown, Clipboard, Download, Leaf, Menu, Play, Sparkles, Volume2, X } from "lucide-react";

const journalCss = `
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Fraunces:opsz,wght@9..144,600;9..144,700&display=swap');
.gaj{--ink:#2b2631;--plum:#4a1f37;--berry:#a83c52;--marigold:#f1b24a;--paper:#fffaf1;--pink:#f7e6df;--sage:#cad9c2;--line:#e9d8ca;min-height:100dvh;background:#f6eee7;color:var(--ink);font-family:'DM Sans',sans-serif}
.gaj *{box-sizing:border-box}.gaj button{font:inherit}.gaj a{color:inherit}
.gaj-shell{max-width:1180px;margin:0 auto;padding:0 28px}.gaj-top{height:76px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}
.gaj-brand{display:flex;align-items:center;gap:11px;font-weight:700;letter-spacing:-.02em;color:var(--plum)}.gaj-mark{width:35px;height:35px;border-radius:11px 11px 11px 4px;background:var(--plum);display:grid;place-items:center;color:var(--marigold);font-family:Fraunces;font-size:23px}.gaj-word{font-size:14px}.gaj-word small{display:block;color:#9d807b;font-size:10px;font-weight:500;letter-spacing:.1em;text-transform:uppercase;margin-top:2px}
.gaj-topnav{display:flex;gap:28px;color:#81676c;font-size:12px}.gaj-topnav a{text-decoration:none}.gaj-topnav a:hover{color:var(--berry)}.gaj-menu{display:none;background:none;border:0;color:var(--plum)}
.gaj-hero{padding:62px 0 54px;background:var(--paper);border-bottom:1px solid var(--line);position:relative;overflow:hidden}.gaj-hero:after{content:"";position:absolute;right:-90px;top:-170px;width:480px;height:480px;border-radius:50%;border:1px solid #e9cdbb;opacity:.7}
.gaj-hero-grid{display:grid;grid-template-columns:1fr 390px;gap:70px;align-items:center;position:relative;z-index:1}.gaj-eyebrow{font-size:11px;text-transform:uppercase;letter-spacing:.18em;font-weight:700;color:var(--berry);display:flex;align-items:center;gap:9px}.gaj-eyebrow span{height:1px;width:24px;background:var(--berry)}
.gaj h1,.gaj h2,.gaj h3{font-family:Fraunces,serif;color:var(--plum);font-weight:600}.gaj h1{font-size:clamp(43px,6vw,76px);line-height:.99;letter-spacing:-.055em;margin:19px 0 23px;max-width:670px}.gaj h1 em{color:var(--berry);font-style:normal}.gaj-lede{max-width:570px;font-size:17px;line-height:1.65;color:#735c61}.gaj-byline{font-size:11px;color:#9b7c78;margin-top:25px}
.gaj-count{margin-top:30px;display:flex;gap:8px;flex-wrap:wrap}.gaj-date{background:#f5e4d8;border:1px solid #edcdbb;border-radius:13px;padding:13px 16px;min-width:145px}.gaj-date b{display:block;font-family:Fraunces;color:var(--plum);font-size:18px}.gaj-date span{display:block;color:#8f6c6b;font-size:10px;margin-top:3px;text-transform:uppercase;letter-spacing:.08em}
.gaj-art{height:350px;border-radius:180px 180px 24px 24px;background:#eab9a3;position:relative;display:grid;place-items:center;box-shadow:11px 15px 0 #f1d8c9;overflow:hidden}.gaj-art:before,.gaj-art:after{content:"";position:absolute;border-radius:50%;border:1px solid rgba(74,31,55,.2)}.gaj-art:before{width:250px;height:250px}.gaj-art:after{width:310px;height:310px}.gaj-sun{width:145px;height:145px;border-radius:50%;background:var(--marigold);position:relative;z-index:2;display:grid;place-items:center;color:var(--plum);font:700 74px Fraunces;transform:rotate(-7deg)}.gaj-sun:before{content:"";position:absolute;inset:15px;border:1px solid rgba(74,31,55,.2);border-radius:50%}.gaj-note{position:absolute;bottom:21px;left:25px;background:var(--paper);padding:11px 15px;border-radius:3px 12px 12px 12px;font:600 12px Fraunces;color:var(--plum);transform:rotate(-4deg);z-index:3}
.gaj-sticky{position:sticky;top:0;z-index:10;background:rgba(246,238,231,.95);backdrop-filter:blur(12px);border-bottom:1px solid var(--line)}.gaj-sticky-inner{display:flex;align-items:center;gap:12px;overflow:auto;padding:13px 0;scrollbar-width:none}.gaj-sticky a{white-space:nowrap;text-decoration:none;font-size:11px;font-weight:600;color:#8a6d70;padding:9px 13px;border-radius:99px}.gaj-sticky a:first-child{background:var(--plum);color:#fff5ed}
.gaj-main{max-width:980px;margin:0 auto;padding:65px 28px}.gaj-section{scroll-margin-top:70px;margin-bottom:92px}.gaj-kicker{font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:var(--berry);font-weight:700;margin-bottom:13px}.gaj h2{font-size:clamp(34px,4.5vw,52px);line-height:1.03;letter-spacing:-.04em;margin:0 0 16px}.gaj-intro{font-size:16px;line-height:1.7;color:#715b60;max-width:700px}
.gaj-paper{background:var(--paper);border:1px solid #ead9cc;border-radius:20px;padding:30px;box-shadow:0 5px 0 #ecdcd0}.gaj-story{display:grid;grid-template-columns:1.1fr .9fr;gap:30px;align-items:center}.gaj-story p{color:#6e585a;line-height:1.8}.gaj-quote{border-left:3px solid var(--marigold);padding:4px 0 4px 18px;font:600 21px/1.35 Fraunces;color:var(--plum);margin:22px 0}.gaj-tag{display:inline-flex;gap:6px;align-items:center;background:#e6eee2;color:#557052;border-radius:99px;padding:7px 11px;font-size:11px;font-weight:700}
.gaj-timeline{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:28px}.gaj-day{padding:21px;border-top:3px solid var(--marigold);background:#fbf1e8;border-radius:4px 4px 15px 15px}.gaj-day:nth-child(2){border-color:var(--berry)}.gaj-day:nth-child(3){border-color:#819b76}.gaj-day strong{font:600 21px Fraunces;color:var(--plum);display:block}.gaj-day label{font-size:10px;letter-spacing:.1em;text-transform:uppercase;color:#9c7670}.gaj-day p{font-size:12px;line-height:1.6;color:#755e61}
.gaj-activity-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:15px;margin-top:28px}.gaj-activity{background:var(--paper);border:1px solid #ead9cc;border-radius:17px;padding:22px;min-height:180px;position:relative}.gaj-activity.tall{grid-row:span 2;background:var(--plum);color:#fff5ed}.gaj-activity h3{font-size:25px;margin:13px 0 8px}.gaj-activity.tall h3{color:#fff2df}.gaj-activity p{font-size:13px;line-height:1.6;color:#80676a}.gaj-activity.tall p{color:#dfc6c4}.gaj-activity-icon{width:34px;height:34px;display:grid;place-items:center;border-radius:10px;background:#f3d6c5;color:var(--berry)}.gaj-activity.tall .gaj-activity-icon{background:#7a4057;color:var(--marigold)}.gaj-arrow{position:absolute;right:20px;bottom:20px;color:var(--berry)}
.gaj-tools{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:28px}.gaj-tool{background:#fcf3e8;border:1px solid #ead9cc;padding:22px;border-radius:17px}.gaj-tool h3{font-size:25px;margin:0 0 10px}.gaj-tool p{font-size:13px;color:#765e62;line-height:1.6}.gaj-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:15px}.gaj-btn{border:0;background:var(--plum);color:#fff4e8;border-radius:99px;padding:10px 15px;font-size:12px;font-weight:700;cursor:pointer;display:inline-flex;align-items:center;gap:7px}.gaj-btn.alt{background:transparent;color:var(--berry);border:1px solid #dcaeb0}.gaj-btn:focus-visible,.gaj-tab:focus-visible,.gaj-faq button:focus-visible{outline:3px solid var(--marigold);outline-offset:3px}.gaj-feedback{font-size:11px;color:#588154;margin-left:4px}
.gaj-tabs{display:flex;gap:7px;margin:15px 0}.gaj-tab{border:1px solid #dfc5b7;background:transparent;border-radius:99px;padding:8px 14px;color:#8e696b;font-size:11px;font-weight:700;cursor:pointer}.gaj-tab.active{background:var(--berry);color:#fff;border-color:var(--berry)}.gaj-copy{font-size:14px;line-height:1.8;color:#6e555a;background:#fffaf2;padding:17px;border-radius:11px;border:1px dashed #e0c8b8}
.gaj-quiz{background:#dfe9d8;border-radius:20px;padding:29px}.gaj-quiz h2{color:#3e5b45}.gaj-question{font-weight:700;color:#3f5745;margin:17px 0 12px}.gaj-options{display:flex;gap:8px;flex-wrap:wrap}.gaj-option{background:#f8fbf3;border:1px solid #b9ccb1;color:#4a684e;border-radius:99px;padding:9px 13px;font-size:12px;cursor:pointer}.gaj-option.correct{background:#63835e;color:#fff;border-color:#63835e}.gaj-quiz-note{font-size:12px;color:#617661;margin-top:14px}
.gaj-faq{border-top:1px solid var(--line)}.gaj-faq button{width:100%;border:0;border-bottom:1px solid var(--line);background:none;padding:18px 0;display:flex;justify-content:space-between;text-align:left;color:var(--plum);font-weight:700;font-size:14px;cursor:pointer}.gaj-faq p{color:#765f62;font-size:13px;line-height:1.65;max-width:750px;margin:0 0 18px}.gaj-faq svg{transition:transform .2s}.gaj-faq.open svg{transform:rotate(180deg)}
.gaj-cta{background:var(--berry);color:#fff4ed;border-radius:22px;padding:42px 38px;display:flex;justify-content:space-between;align-items:center;gap:30px}.gaj-cta h2{color:#fff4ed;font-size:39px;max-width:450px}.gaj-cta p{color:#f7d9d4;max-width:450px;font-size:14px}.gaj-cta .gaj-btn{background:var(--marigold);color:var(--plum)}.gaj-footer{background:var(--plum);color:#d8bab7;padding:30px 0;font-size:11px}.gaj-footer .gaj-shell{display:flex;justify-content:space-between;gap:20px}
@media(max-width:760px){.gaj-shell{padding:0 18px}.gaj-topnav{display:none}.gaj-menu{display:block}.gaj-hero{padding:42px 0}.gaj-hero-grid{grid-template-columns:1fr;gap:38px}.gaj-art{height:270px;max-width:340px;margin:auto;width:100%}.gaj-main{padding:48px 18px}.gaj-story,.gaj-activity-grid,.gaj-tools{grid-template-columns:1fr}.gaj-activity.tall{grid-row:auto}.gaj-timeline{grid-template-columns:1fr}.gaj-cta{display:block;padding:30px 24px}.gaj-cta h2{font-size:34px}.gaj-footer .gaj-shell{display:block}.gaj-footer span{display:block;margin-top:10px}}
@media(prefers-reduced-motion:reduce){.gaj *{scroll-behavior:auto!important;transition:none!important}}
`;

const faqs = [
  ["How do I explain Ganesh Chaturthi to a 2-year-old?", "Keep it simple and sensory: “We’re welcoming a special clay friend named Bappa who loves modaks and big hugs.” Focus on feelings and fun."],
  ["What can a toddler do during the puja?", "Toddlers can help place flowers, gently ring a small bell, clap during the aarti, or simply sit close and watch — participation, not perfection, is what matters."],
  ["Is it safe to do idol immersion with young children present?", "Yes, especially with a small eco-friendly clay idol immersed gently at home in a bucket or tub. Keep the water supervised and the moment calm."],
  ["My child is scared of loud dhol-tasha sounds — what can I do?", "That’s completely normal. Introduce sounds gradually at home, keep a comforting distance, and let your child cover their ears if they need to."],
];

export function FamilyActivityJournal() {
  const [language, setLanguage] = useState<"English" | "मराठी">("English");
  const [copied, setCopied] = useState(false);
  const [quizAnswer, setQuizAnswer] = useState<string | null>(null);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  const [showMenu, setShowMenu] = useState(false);
  const copyText = useMemo(() => language === "English" ? "Ganpati Bappa Morya! Ganesha is kind, wise and loved. We welcome him with flowers, songs and a little modak. May every new beginning feel brave and bright." : "गणपती बाप्पा मोरया! गणेशा दयाळू, शहाणा आणि सगळ्यांचा लाडका आहे.", [language]);
  const copy = async () => { await navigator.clipboard?.writeText(copyText); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  return <div className="gaj">
    <style>{journalCss}</style>
    <header className="gaj-top gaj-shell">
      <div className="gaj-brand"><div className="gaj-mark">R</div><div className="gaj-word">Rainbow International<small>Pre-School · Thane</small></div></div>
      <nav className="gaj-topnav"><a href="#make">Make together</a><a href="#speak">Speak & sing</a><a href="#ask">Parent notes</a></nav>
      <button className="gaj-menu" aria-label="Toggle menu" onClick={() => setShowMenu(!showMenu)}>{showMenu ? <X size={20}/> : <Menu size={20}/>}</button>
    </header>
    {showMenu && <nav className="gaj-sticky"><div className="gaj-shell gaj-sticky-inner"><a href="#make" onClick={() => setShowMenu(false)}>Make together</a><a href="#speak" onClick={() => setShowMenu(false)}>Speak & sing</a><a href="#ask" onClick={() => setShowMenu(false)}>Parent notes</a></div></nav>}
    <section className="gaj-hero"><div className="gaj-shell gaj-hero-grid"><div>
      <div className="gaj-eyebrow"><span/>A family activity journal</div>
      <h1>Welcome home,<br/><em>Bappa.</em></h1>
      <p className="gaj-lede">A gentle, hands-on guide for the little years — stories to share, things to make, words to say, and small moments to remember.</p>
      <div className="gaj-byline">BY RAINBOW PRESCHOOLS, THANE · GANESH CHATURTHI 2026</div>
      <div className="gaj-count"><div className="gaj-date"><b>14 Sep</b><span>Ganesh Sthapana · Monday</span></div><div className="gaj-date"><b>25 Sep</b><span>Anant Chaturdashi · Friday</span></div></div>
    </div><div className="gaj-art" aria-label="Abstract festival journal cover"><div className="gaj-sun">ॐ</div><div className="gaj-note">Ten days of<br/>little wonders</div></div></div></section>
    <nav className="gaj-sticky" aria-label="Chapter navigation"><div className="gaj-shell gaj-sticky-inner"><a href="#welcome">01 Welcome</a><a href="#make">02 Make</a><a href="#speak">03 Speak & sing</a><a href="#quiz">04 Discover</a><a href="#ask">05 Parent notes</a></div></nav>
    <main className="gaj-main">
      <section className="gaj-section" id="welcome"><div className="gaj-kicker">Chapter 01 · Begin with wonder</div><h2>Make room for a<br/>beautiful hello.</h2><p className="gaj-intro">Ganesh Chaturthi is the ten-day festival when we welcome a special friend — Ganpati Bappa, the elephant-headed friend who loves modaks, listens with big ears, and helps us feel brave. For little learners, it is a season of colours, music, sweet treats and cuddly stories.</p><div className="gaj-paper gaj-story" style={{marginTop:28}}><div><span className="gaj-tag"><Leaf size={13}/> A story for little ones</span><p>Once upon a time, Parvati made a little boy from soft clay to guard her door. He stood proudly at his post. When the family understood who he was, everyone came to bless him — and Ganesha, wise, kind and very loved, opened his eyes with the sweetest elephant face.</p><div className="gaj-quote">“Wonder, not worksheets.”<br/><small style={{font:'12px DM Sans',color:'#9c7670'}}>— Rainbow’s way of celebrating</small></div></div><div className="gaj-paper" style={{background:"#f4ddcf",boxShadow:"none",transform:"rotate(2deg)"}}><div className="gaj-kicker">A tiny prompt</div><h3 style={{fontSize:28}}>What do you notice?</h3><p style={{fontSize:13}}>Point to Bappa’s big ears, kind eyes and round tummy. Ask your child what they think he might like to hear today.</p></div></div></section>
      <section className="gaj-section" id="make"><div className="gaj-kicker">Chapter 02 · Hands at work</div><h2>Little hands,<br/>festival-sized joy.</h2><p className="gaj-intro">Pick one activity for today. There is no perfect finish — a child’s fingerprints, questions and wobbly lines are the keepsake.</p><div className="gaj-activity-grid"><article className="gaj-activity tall"><div className="gaj-activity-icon"><Sparkles size={18}/></div><h3>Make a clay Bappa</h3><p>Shape a small eco-friendly clay idol together. Notice how the material changes under your fingers. Let your child choose one flower, leaf or paper detail for the altar.</p><div className="gaj-actions"><button className="gaj-btn" onClick={() => document.getElementById("speak")?.scrollIntoView({behavior:"smooth"})}>Next: say hello <ArrowRight size={14}/></button></div></article><article className="gaj-activity"><div className="gaj-activity-icon"><Play size={16}/></div><h3>Sound walk</h3><p>Listen for bells, claps and dhol-tasha. Keep the volume gentle and let your child choose when to pause.</p><ArrowRight className="gaj-arrow" size={18}/></article><article className="gaj-activity"><div className="gaj-activity-icon"><Leaf size={16}/></div><h3>Modak shapes</h3><p>Roll, pinch and count soft dough. Store-bought modaks work beautifully too, with supervision.</p><ArrowRight className="gaj-arrow" size={18}/></article></div><div className="gaj-timeline"><div className="gaj-day"><label>Day 01</label><strong>Welcome</strong><p>Flowers, a song and the first modak.</p></div><div className="gaj-day"><label>Days 02–09</label><strong>Notice</strong><p>An evening aarti, a tiny act of care.</p></div><div className="gaj-day"><label>Day 10</label><strong>Goodbye</strong><p>A loving farewell and a promise to return.</p></div></div></section>
      <section className="gaj-section" id="speak"><div className="gaj-kicker">Chapter 03 · Words to carry</div><h2>Say it softly.<br/>Sing it together.</h2><p className="gaj-intro">Short words are enough for a young speaker. Copy a line for show-and-tell, or make it your family’s festival refrain.</p><div className="gaj-tools"><div className="gaj-tool"><h3>My first little speech</h3><div className="gaj-tabs"><button className={`gaj-tab ${language==="English"?"active":""}`} onClick={() => setLanguage("English")}>English</button><button className={`gaj-tab ${language==="मराठी"?"active":""}`} onClick={() => setLanguage("मराठी")}>मराठी</button></div><div className="gaj-copy">{copyText}</div><div className="gaj-actions"><button className="gaj-btn" onClick={copy}>{copied ? <Check size={14}/> : <Clipboard size={14}/>} {copied ? "Copied" : "Copy words"}</button>{copied && <span className="gaj-feedback">Ready to share</span>}</div></div><div className="gaj-tool"><h3>Rhyme & rhythm</h3><p>Try this original little rhyme with a clap on each line:</p><div className="gaj-copy">Big ears listening,<br/>Kind eyes bright,<br/>Bappa brings courage<br/>To our hearts tonight.</div><div className="gaj-actions"><button className="gaj-btn alt"><Volume2 size={14}/> Read aloud</button></div></div></div></section>
      <section className="gaj-section" id="quiz"><div className="gaj-quiz"><div className="gaj-kicker">Chapter 04 · Discover</div><h2>Can you spot<br/>Bappa’s friend?</h2><p className="gaj-intro" style={{color:"#617661"}}>A tiny quiz for little explorers. Choose together — then talk about why.</p><div className="gaj-question">Who is Ganesha’s tiny helper?</div><div className="gaj-options">{["A moon","A mouse","A peacock"].map(option => <button key={option} className={`gaj-option ${quizAnswer===option?"correct":""}`} onClick={() => setQuizAnswer(option)}>{quizAnswer===option && <Check size={13} style={{verticalAlign:"-2px",marginRight:4}}/>}{option}</button>)}</div>{quizAnswer && <div className="gaj-quiz-note">{quizAnswer === "A mouse" ? "Yes — Mushak is Ganesha’s little helper. Even the smallest of us can do big things." : "A thoughtful guess. Try again — look for the tiny friend who travels with Bappa."}</div>}</div></section>
      <section className="gaj-section" id="ask"><div className="gaj-kicker">Chapter 05 · For grown-ups</div><h2>Room for every<br/>kind of celebration.</h2><p className="gaj-intro">Participation, not perfection, is what matters. Keep the sensory world gentle, the story short and the goodbye meaningful.</p><div className="gaj-faq">{faqs.map(([q,a],i) => <div className={`gaj-faq ${openFaq===i?"open":""}`} key={q}><button onClick={() => setOpenFaq(openFaq===i ? null : i)} aria-expanded={openFaq===i}>{q}<ChevronDown size={17}/></button>{openFaq===i && <p>{a}</p>}</div>)}</div></section>
      <section className="gaj-section"><div className="gaj-cta"><div><div className="gaj-kicker" style={{color:"#f7d18b"}}>Keep the page</div><h2>Make a wish card for Bappa.</h2><p>Write one small wish, choose a colour, and save a keepsake from your family’s festival book.</p></div><button className="gaj-btn" onClick={() => alert("Your wish card is ready to personalise in the Rainbow family journal.")}><Download size={15}/> Create wish card</button></div></section>
    </main>
    <footer className="gaj-footer"><div className="gaj-shell"><span>Rainbow International Pre-School · Thane</span><span>Grow · Learn · Celebrate together</span></div></footer>
  </div>;
}