// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ganesh-redesign/Current.tsx": () => import("../components/mockups/ganesh-redesign/Current.tsx"),
  "./components/mockups/ganesh-redesign/FamilyActivityJournal.tsx": () => import("../components/mockups/ganesh-redesign/FamilyActivityJournal.tsx"),
  "./components/mockups/ganesh-redesign/FestivalJourney.tsx": () => import("../components/mockups/ganesh-redesign/FestivalJourney.tsx"),
  "./components/mockups/ganesh-redesign/StorybookSanctuary.tsx": () => import("../components/mockups/ganesh-redesign/StorybookSanctuary.tsx")
};
