const BASE_URL = "https://www.rainbowpreschools.com";

export const ABOUT_PAGE_COPY = {
  title: "About Rainbow Preschool International, Thane | Since 2007",
  description: "Since 2007, Rainbow Preschool International has run 6 preschool centres in Thane for ages 1.5–5.5, with ECCE-trained female teachers and a play-based, NEP 2020-aligned curriculum.",
  dateIso: "2026-09-29",
  dateDisplay: "29 September 2026",
  ogImage: `${BASE_URL}/images/og/about-1200x630.jpg`,
  ogImageAlt: "About Rainbow Preschool International in Thane",
  heroHeading: "About Rainbow Preschool International",
  heroTagline: "Preschools in Thane since 2007.",
  heroLinks: {
    visit: "/contact",
    whatsapp: "https://wa.me/918291568972?text=Hi%2C%20I%20would%20like%20to%20know%20more%20about%20Rainbow%20Preschool",
    programmes: "/programmes",
  },
  stats: [
    { value: "1 Lac+", label: "Happy Students" },
    { value: "18+", label: "Years" },
    { value: "6", label: "Centres in Thane" },
    { value: "4.9", label: "Google Rating (487 reviews)" },
  ],
  storyHeading: "Our Story",
  programmesHeading: "Our Programmes",
  chairpersonHeading: "A Note from Our Chairperson",
  curriculumHeading: "Rainbow Preschool International Curriculum",
  trustHeading: "Why Parents Trust Rainbow Preschool International",
  centresHeading: "Our 6 Centres Across Thane",
  faqHeading: "Frequently Asked Questions",
  journeyHeading: "Our Journey",
  coordinatorsHeading: "Our Academic Coordinators",
  exploreHeading: "Explore Rainbow Preschool",
  storyParagraphs: [
    "Rainbow Preschool International started in Thane in 2007 with one aim: to give young children a safe, happy place to begin learning. Today we run six centres across Thane: Aggarwal (Manpada), Hariniwas, Anand Nagar, Dhokali, Kalwa and Kasarvadavali. Our play-based, NEP 2020-aligned approach helps children learn with confidence through hands-on exploration and discovery.",
  ],
  storyImages: [
    { src: "/images/optimized/DSC00002.webp", alt: "Children enjoying activities at Rainbow Preschool", width: 400, height: 400 },
    { src: "/images/optimized/DSC00010.webp", alt: "Child at Rainbow Preschool", width: 400, height: 400 },
    { src: "/images/optimized/DSC00051.webp", alt: "Kids at preschool", width: 400, height: 400 },
    { src: "/images/optimized/DSC00054.webp", alt: "Children playing with colorful toys", width: 400, height: 400 },
  ],
  programmesIntro: "We offer age-appropriate programmes for children aged 1.5 to 5.5 years.",
  daycareIntro: "Happy Times daycare (ages 2–8) runs at our Aggarwal, Anand Nagar and Dhokali centres.",
  daycareLinkText: "Happy Times daycare",
  daycareHref: "/happy-times",
  programmes: [
    { id: "playgroup", title: "Playgroup", href: "/playgroup", age: "1.5–2.5 years", copy: "Your toddler's first gentle steps into play-based learning and socialisation." },
    { id: "nursery", title: "Nursery", href: "/nursery", age: "2.5–3.5 years", copy: "Building early literacy, numeracy, and confidence through creative exploration." },
    { id: "kindergarten", title: "Kindergarten: Jr. KG and Sr. KG", href: "/kindergarten", age: "3.5–5.5 years", copy: "Full school-readiness programme covering reading, writing, maths, and life skills." },
  ],
  chairpersonIntro: "At Rainbow, parents play a vital role in our journey towards excellence. Together, we shape each child into a confident, skilled learner with a global perspective.",
  chairpersonFullNote: [
    "\"Live as if you were to die tomorrow, Learn as if you were to live forever.\" – Mahatma Gandhi",
    "Just like our beloved Mahatma Gandhi Ji believed, Learning is essential for an individual's growth. And when we hear the word Learning, the word Education comes to our mind as they both are closely related.",
    "Education is a joint venture: an association between the school and the home to ensure that children become successful in whatever they choose to pursue. Right education materializes out of co-operation among the learners, mentors, parents and the community.",
    "I assure you that the entire team of Rainbow Preschool International helps shape each child into an intelligent, skilled and committed Indian citizen with a global perspective. I look forward to your kind association, valuable support and a healthy rapport that shall assist us in the holistic development of each child.",
    "Yours Sincerely, Mrs. Akila Balbale",
  ],
  curriculumIntro: "Our curriculum is holistic, play-based and aligned with NEP 2020, designed to nurture every aspect of your child's growth through joyful learning.",
  keyPrinciples: [
    "Holistic Development",
    "Play-Based Learning",
    "Developmentally Appropriate Practice",
    "Cultural Sensitivity",
    "Focus on Process",
    "Family & Community Engagement",
  ],
  effectiveImplementation: [
    "Observation & Assessment",
    "Intentional Teaching",
    "Differentiated Instruction",
    "Enriching Environment",
  ],
  learningDomains: [
    { domain: "Physical Development", areas: "Gross motor, fine motor, health & wellness" },
    { domain: "Cognitive Development", areas: "Problem-solving, early math, early science inquiry" },
    { domain: "Language & Communication", areas: "Literacy, expressive/receptive language, storytelling" },
    { domain: "Social & Emotional", areas: "Self-awareness, self-regulation, relationships" },
    { domain: "Creative & Aesthetic", areas: "Music, dance, arts, imagination, dramatic play" },
  ],
  trustCards: [
    { title: "Safety & CCTV", description: "CCTV-monitored classrooms and secure premises" },
    { title: "100% Female Staff", description: "Caring, nurturing environment" },
    { title: "ECCE-Trained Teachers", description: "Trained in Early Childhood Care and Education" },
    { title: "Hygiene & Cleanliness", description: "Toys and classrooms sanitised several times a day" },
    { title: "Play-Based Learning", description: "Joyful, hands-on education" },
    { title: "Parent Partnership", description: "Daily updates and monthly progress reports" },
  ],
  centres: [
    { name: "Aggarwal (Manpada)", area: "Near Khewra Circle · Playgroup to Grade 4", linkText: "View Manpada centre →", href: "/preschool-in-manpada-thane" },
    { name: "Hariniwas", area: "Naupada, Central Thane · Playgroup to Grade 3", linkText: "View Hariniwas centre →", href: "/preschool-in-hariniwas-thane" },
    { name: "Anand Nagar", area: "Majiwada, opposite Tropical Lagoon · Playgroup to Grade 2", linkText: "View Anand Nagar centre →", href: "/preschool-in-anand-nagar-thane" },
    { name: "Dhokali", area: "Kolshet Road · Playgroup to Sr. KG", linkText: "View Dhokali centre →", href: "/preschool-in-dhokali-thane" },
    { name: "Kalwa", area: "Eastern Thane · Playgroup to Grade 4", linkText: "View Kalwa centre →", href: "/preschool-in-kalwa-thane" },
    { name: "Kasarvadavali", area: "Ghodbunder Road · Playgroup to Grade 3", linkText: "View Kasarvadavali centre →", href: "/preschool-in-kasarvadavali-thane" },
  ],
  transportNote: "GPS-enabled in-house transport is available at all 6 centres.",
  faqs: [
    {
      question: "When did Rainbow Preschool start?",
      answer: "Rainbow Preschool International started in Thane in 2007 and now runs six centres across Thane.",
    },
    {
      question: "How many centres does Rainbow Preschool have in Thane?",
      answer: "Rainbow Preschool International has 6 centres across Thane: Aggarwal (Manpada), Hariniwas, Anand Nagar, Dhokali, Kalwa and Kasarvadavali.",
    },
    {
      question: "Which programmes are offered?",
      answer: "Rainbow Preschool International offers Playgroup, Nursery, Kindergarten, and Happy Times daycare (ages 2–8, at 3 centres).",
    },
    {
      question: "What age groups are accepted?",
      answer: "Children aged 1.5 to 5.5 years: Playgroup (1.5–2.5), Nursery (2.5–3.5), Jr. KG (3.5–4.5) and Sr. KG (4.5–5.5). Age is counted as of 1 June of the academic year.",
    },
    {
      question: "How does Rainbow support child safety?",
      answer: "Through CCTV-monitored classrooms, 100% female ECCE-trained teaching staff, child-friendly classrooms, and toys and classrooms sanitised several times a day.",
    },
    {
      question: "How can parents book a visit?",
      answer: "Parents can call 82915 68972, send a WhatsApp enquiry, or fill in the contact form to book a campus visit.",
    },
    {
      question: "Does Rainbow provide transport?",
      answer: "Yes. GPS-enabled in-house transport is available at all 6 centres.",
    },
    {
      question: "What happens after Sr. KG?",
      answer: "At five of our centres, children can continue into primary classes: up to Grade 4 at Aggarwal (Manpada) and Kalwa, Grade 3 at Hariniwas and Kasarvadavali, and Grade 2 at Anand Nagar. Our group's K–12 school, Rainbow International School, is in Brahmand, Thane West.",
    },
  ],
  milestones: [
    { year: "2007", title: "Founded", description: "Rainbow Preschool International started its journey in Thane." },
    { year: "2010", title: "Expansion", description: "Opened additional centres to serve more families." },
    { year: "2018", title: "Awarded", description: "“Best Preschool in Thane”." },
    { year: "2020", title: "Digital learning", description: "Moved classes online during school closures. Also received the “Cleanest Preschool” award." },
    { year: "2021", title: "Awarded", description: "“Most Promising Preschool Chain of the Year”." },
    { year: "2022", title: "Awarded", description: "“Emerging Preschool Chain of the Year”." },
    { year: "2023", title: "Awarded", description: "“Best Preschool in Thane” again." },
    { year: "2025", title: "1,00,000+ students", description: "Celebrating generations of happy learners." },
  ],
  coordinatorIntro: "The educators who guide our curriculum at each centre.",
  coordinators: [
    { name: "Harsha Sutar", centre: "Dhokali Centre", img: "/images/coordinators/harsha-sutra.webp", width: 128, height: 128 },
    { name: "Gauri Randhir", centre: "Anand Nagar Centre", img: "/images/coordinators/gauri-randhir.webp", width: 128, height: 128 },
    { name: "Swapnali Pandit", centre: "Aggarwal Centre (Manpada)", img: "/images/coordinators/swapnali-pandit.webp", width: 128, height: 128 },
    { name: "Shweta Chheda", centre: "Hariniwas Centre", img: "/images/coordinators/shweta-chheda.webp", width: 128, height: 128 },
    { name: "Nilsy Jain", centre: "Kasarvadavali Centre", img: "/images/coordinators/nilsy-jain.webp", width: 128, height: 128 },
    { name: "Mittal Shah", centre: "Kalwa Centre", img: "/images/coordinators/mittal-shah.webp", width: 128, height: 128 },
  ],
  exploreLinks: [
    { text: "Preschools in Thane", url: "/play-school-near-me" },
    { text: "Find Nearest Centre", url: "/play-school-near-me" },
    { text: "Admission Process", url: "/preschool-admissions" },
    { text: "Photo Gallery", url: "/gallery" },
  ],
} as const;

export const ABOUT_PAGE_SCHEMA = {
  "@context": "https://schema.org",
  "@type": "AboutPage",
  "@id": `${BASE_URL}/about#webpage`,
  name: ABOUT_PAGE_COPY.heroHeading,
  description: ABOUT_PAGE_COPY.description,
  url: `${BASE_URL}/about`,
  dateModified: ABOUT_PAGE_COPY.dateIso,
  inLanguage: "en-IN",
  about: { "@id": `${BASE_URL}/#organization` },
  publisher: { "@id": `${BASE_URL}/#organization` },
};