export const ABOUT_PAGE_COPY = {
  heroHeading: "About Rainbow Preschool International",
  heroTagline: "Trusted preschool chain in Thane since 2007.",
  stats: [
    { value: "1 Lac+", label: "Happy Students" },
    { value: "18+", label: "Years of Excellence" },
    { value: "6", label: "Centres in Thane" },
    { value: "4.9", label: "Google Rating" },
  ],
  storyHeading: "Our Story",
  programmesHeading: "Our Programmes",
  chairpersonHeading: "A Note from Our Chairperson",
  curriculumHeading: "Rainbow Preschool International Curriculum",
  trustHeading: "Why Parents Trust Rainbow Preschool",
  centresHeading: "Our 6 Centres Across Thane",
  faqHeading: "Frequently Asked Questions",
  journeyHeading: "Our Journey",
  coordinatorsHeading: "Our Academic Coordinators",
  exploreHeading: "Explore Rainbow Preschool",
  storyParagraphs: [
    "Rainbow Preschool International was founded in 2007 with a simple vision: to provide the finest early childhood education in Thane for every child. Today, we have grown to six thriving centres across Thane West.",
    "Our play-based approach helps children learn confidently and joyfully, preparing them for a brighter future through hands-on exploration and discovery.",
  ],
  storyImages: [
    { src: "/images/optimized/DSC00002.webp", alt: "Children enjoying activities at Rainbow Preschool", width: 400, height: 400 },
    { src: "/images/optimized/DSC00010.webp", alt: "Child at Rainbow Preschool", width: 400, height: 400 },
    { src: "/images/optimized/DSC00051.webp", alt: "Kids at preschool", width: 400, height: 400 },
    { src: "/images/optimized/DSC00054.webp", alt: "Children playing with colorful toys", width: 400, height: 400 },
  ],
  programmesIntro: "We offer age-appropriate programmes for children aged 1.5 to 6 years.",
  programmes: [
    { id: "playgroup", title: "Playgroup", href: "/playgroup", age: "1.5–2.5 years", copy: "Your toddler's first gentle steps into play-based learning and socialisation." },
    { id: "nursery", title: "Nursery", href: "/nursery", age: "2.5–3.5 years", copy: "Building early literacy, numeracy, and confidence through creative exploration." },
    { id: "kindergarten", title: "Kindergarten", href: "/kindergarten", age: "3.5–5.5 years", copy: "Full school-readiness programme covering reading, writing, maths, and life skills." },
  ],
  chairpersonIntro: "At Rainbow, parents play a vital role in our journey towards excellence. Together, we shape each child into a confident, skilled learner with a global perspective.",
  chairpersonFullNote: [
    "\"Live as if you were to die tomorrow, Learn as if you were to live forever.\" – Mahatma Gandhi",
    "Just like our beloved Mahatma Gandhi Ji believed, Learning is essential for an individual's growth. And when we hear the word Learning, the word Education comes to our mind as they both are co-related.",
    "Education is a joint venture: an association between the school and the home to ensure that children become successful in whatever they choose to pursue. Right education materializes out of co-operation among the learners, mentors, parents and the community.",
    "I assure you that the entire team of Rainbow Preschool International helps shape each child into an intelligent, skilled and committed Indian citizen with a global perspective. I look forward to your kind association, valuable support and a healthy rapport that shall assist us in the holistic development of each child.",
    "Yours Sincerely, Mrs. Akila Balbale",
  ],
  curriculumIntro: "Our curriculum is holistic, play-based, and developmentally appropriate, designed to nurture every aspect of your child's growth through joyful learning experiences.",
  keyPrinciples: [
    "Holistic Development",
    "Play-Based Learning",
    "Developmentally Appropriate Practice",
    "Cultural Sensitivity",
    "Focus on Process",
    "Family & Community Engagement",
  ],
  effectiveImplementation: [
    "Observation & Assessment",
    "Intentional Teaching",
    "Differentiated Instruction",
    "Enriching Environment",
  ],
  learningDomains: [
    { domain: "Physical Development", areas: "Gross motor, fine motor, health & wellness" },
    { domain: "Cognitive Development", areas: "Problem-solving, early math, early science inquiry" },
    { domain: "Language & Communication", areas: "Literacy, expressive/receptive language, storytelling" },
    { domain: "Social & Emotional", areas: "Self-awareness, self-regulation, relationships" },
    { domain: "Creative & Aesthetic", areas: "Music, dance, arts, imagination, dramatic play" },
  ],
  trustCards: [
    { title: "Safety & CCTV", description: "24/7 surveillance and secure premises" },
    { title: "100% Female Staff", description: "Caring, nurturing environment" },
    { title: "Certified Teachers", description: "Trained early childhood educators" },
    { title: "Hygiene & Cleanliness", description: "Sanitized spaces daily" },
    { title: "Play-Based Learning", description: "Joyful, hands-on education" },
    { title: "Parent Partnership", description: "Regular updates and involvement" },
  ],
  centres: [
    { name: "Manpada", area: "Near Khewra Circle", href: "/preschool-in-manpada-thane" },
    { name: "Hariniwas", area: "Naupada, Central Thane", href: "/preschool-in-hariniwas-thane" },
    { name: "Anand Nagar", area: "Majiwada, opposite Tropical Lagoon", href: "/preschool-in-anand-nagar-thane" },
    { name: "Dhokali", area: "Kolshet Road", href: "/preschool-in-dhokali-thane" },
    { name: "Kalwa", area: "Eastern Thane", href: "/preschool-in-kalwa-thane" },
    { name: "Kasarvadavali", area: "Ghodbunder Road", href: "/preschool-in-kasarvadavali-thane" },
  ],
  faqs: [
    {
      question: "When did Rainbow Preschool start?",
      answer: "Rainbow Preschool International started in Thane in 2007 and has grown into a trusted early learning network for young children.",
    },
    {
      question: "How many centres does Rainbow Preschool have in Thane?",
      answer: "Rainbow Preschool has 6 centres across Thane: Manpada, Hariniwas, Anand Nagar, Dhokali, Kalwa, and Kasarvadavali.",
    },
    {
      question: "Which programmes are offered?",
      answer: "Rainbow Preschool offers Playgroup, Nursery, Kindergarten, and Happy Times extended care for young children.",
    },
    {
      question: "What age groups are accepted?",
      answer: "Rainbow offers age-appropriate early learning programmes for children aged 1.5 to 6 years.",
    },
    {
      question: "How does Rainbow support child safety?",
      answer: "Rainbow supports child safety through CCTV-enabled campuses, 100% female teaching staff, secure pickup practices, child-friendly classrooms, and daily hygiene routines.",
    },
    {
      question: "How can parents book a visit?",
      answer: "Parents can call 82915 68972, send a WhatsApp enquiry, or fill in the contact form to book a campus visit.",
    },
  ],
  milestones: [
    { year: "2007", title: "Founded", description: "Rainbow Preschool started its journey in Thane" },
    { year: "2010", title: "Expansion", description: "Opened additional centres to serve more families" },
    { year: "2020", title: "Digital Learning", description: "Successfully adapted to online learning" },
    { year: "2025", title: "1,00,000+ Alumni", description: "Celebrating generations of happy learners" },
  ],
  coordinatorIntro: "The dedicated educators who guide our curriculum and ensure every child's learning journey is exceptional.",
  coordinators: [
    { name: "Harsha Sutar", centre: "Dhokali Centre", img: "/images/coordinators/harsha-sutra.webp", width: 128, height: 128 },
    { name: "Gauri Randhir", centre: "Anand Nagar Centre", img: "/images/coordinators/gauri-randhir.webp", width: 128, height: 128 },
    { name: "Swapnali Pandit", centre: "Aggarwal Centre", img: "/images/coordinators/swapnali-pandit.webp", width: 128, height: 128 },
    { name: "Shweta Chheda", centre: "Hariniwas Centre", img: "/images/coordinators/shweta-chheda.webp", width: 128, height: 128 },
    { name: "Nilsy Jain", centre: "Kasarvadavali Centre", img: "/images/coordinators/nilsy-jain.webp", width: 128, height: 128 },
    { name: "Mittal Shah", centre: "Kalwa Centre", img: "/images/coordinators/mittal-shah.webp", width: 128, height: 128 },
  ],
  exploreLinks: [
    { text: "Award-Winning Preschool", url: "/play-school-near-me" },
    { text: "Find Nearest Centre", url: "/play-school-near-me" },
    { text: "Admission Process", url: "/preschool-admissions" },
    { text: "Photo Gallery", url: "/gallery" },
  ],
} as const;