export const ADMISSIONS_PAGE_COPY = {
  meta: {
    title: "Preschool Admissions in Thane | Rainbow Preschool",
    description: "Apply for preschool admission at Rainbow Preschool Thane. Playgroup, Nursery & KG open — age criteria, documents, fee structure & step-by-step process.",
    keywords: "preschool admissions in thane, preschool admission near me, nursery admission thane, kindergarten admission thane, playgroup admission thane, preschool admission process, preschool admission form, preschool admission enquiry",
  },
  hero: {
    eyebrow: "Admissions Open 2026–27",
    h1: "Preschool Admissions in Thane",
    subheadline: "Start your child's early learning journey with Rainbow Preschool International. We offer admissions for Playgroup, Nursery, Jr. KG, and Sr. KG across multiple centres in Thane.",
    supporting: "Explore age criteria, admission process, centre options, and submit an enquiry to speak with our admissions team.",
    form: {
      title: "Start Your Admission Enquiry",
      subtext: "Fill the form and our admissions team will contact you within 24 hours",
    },
  },
  programmes: [
    { label: "Playgroup", age: "1.5 – 2.5 years", href: "/playgroup", color: "bg-yellow-50 dark:bg-yellow-900/30 border-yellow-200 dark:border-yellow-800" },
    { label: "Nursery", age: "2.5 – 3.5 years", href: "/nursery", color: "bg-blue-50 dark:bg-blue-900/30 border-blue-200 dark:border-blue-800" },
    { label: "Jr. KG", age: "3.5 – 4.5 years", href: "/kindergarten", color: "bg-green-50 dark:bg-green-900/30 border-green-200 dark:border-green-800" },
    { label: "Sr. KG", age: "4.5 – 5.5 years", href: "/kindergarten", color: "bg-purple-50 dark:bg-purple-900/30 border-purple-200 dark:border-purple-800" },
  ],
  admissionSteps: [
    { icon: "clipboardList", step: "01", title: "Submit an Enquiry", desc: "Fill the online form on this page, call us at 82915 68972, or walk into any Rainbow Preschool centre in Thane." },
    { icon: "mapPin", step: "02", title: "Schedule a Campus Visit", desc: "Our admissions team will arrange a guided tour of your preferred centre — classrooms, play areas, and safety installations." },
    { icon: "messageCircle", step: "03", title: "Speak with the Admissions Team", desc: "Discuss your child's age, preferred programme, batch timing, and any questions with our experienced admissions team." },
    { icon: "fileText", step: "04", title: "Complete the Registration Form", desc: "Fill the formal admission registration form and submit it to the centre to reserve your child's seat." },
    { icon: "check", step: "05", title: "Submit Required Documents", desc: "Provide the necessary documents — birth certificate, ID proof, photographs, and address proof — to complete the admission file." },
    { icon: "graduationCap", step: "06", title: "Confirm Admission & Onboarding", desc: "Pay the admission fee to confirm the seat. Attend our parent orientation session before your child's first day." },
  ],
  ageCriteria: [
    { programme: "Playgroup", age: "1.5 – 2.5 years", desc: "Sensory play, music, movement, and first social introduction. Focuses on separation comfort, basic routines, and exploration.", href: "/playgroup", color: "border-l-yellow-400" },
    { programme: "Nursery", age: "2.5 – 3.5 years", desc: "Phonics, early numeracy, storytelling, and fine motor skills. Children build language, independence, and creative confidence.", href: "/nursery", color: "border-l-blue-400" },
    { programme: "Jr. KG", age: "3.5 – 4.5 years", desc: "Pre-reading, writing, and early maths. Project-based learning, science activities, and structured group work.", href: "/kindergarten", color: "border-l-green-400" },
    { programme: "Sr. KG", age: "4.5 – 5.5 years", desc: "Full school-readiness — reading fluency, writing, mental maths, and general knowledge for a smooth Class 1 transition.", href: "/kindergarten", color: "border-l-purple-400" },
  ],
  documents: [
    "Child's birth certificate — original and one photocopy (mandatory for age verification)",
    "4–6 recent passport-size photographs of the child — white background preferred",
    "Parent/guardian ID proof — Aadhaar card, passport, or driving licence of both parents",
    "Address proof — Aadhaar, utility bill, or rental agreement showing current Thane address",
    "Child's Aadhaar card — if available (not mandatory but recommended)",
    "Previous school records — transfer certificate or progress report if applicable",
    "Vaccination card and any relevant medical history or allergy information",
    "Two passport-size photographs of both parents for ID card purposes",
  ],
  admissionTimeline: [
    { icon: "star", period: "October – November", label: "Early Admissions", desc: "Applications open for the next academic year. Early applicants often secure their preferred centre and batch timing." },
    { icon: "calendarDays", period: "December – February", label: "Main Admission Window", desc: "Peak admission period with maximum seat availability across all 6 Rainbow centres in Thane." },
    { icon: "clock", period: "March – May", label: "Final Round", desc: "Seats fill up quickly, especially at popular centres. Early enquiry during this period is strongly recommended." },
    { icon: "mapPin", period: "June Onwards", label: "Academic Year Begins", desc: "Mid-term admissions are accepted subject to seat availability — ideal for families relocating to Thane." },
  ],
  centreImages: {
    manpada: { src: "/images/centres/manpada.webp", alt: "Preschool admissions at Rainbow Preschool Manpada centre, Thane" },
    hariniwas: { src: "/images/centres/hariniwas.webp", alt: "Rainbow Preschool Hariniwas admission centre, Thane" },
    "anand-nagar": { src: "/images/centres/anand-nagar.webp", alt: "Nursery admission at Rainbow Preschool Anand Nagar, Thane" },
    dhokali: { src: "/images/centres/dhokali.webp", alt: "Rainbow Preschool Dhokali centre for playgroup admissions in Thane" },
    kalwa: { src: "/images/centres/kalwa.webp", alt: "Preschool admission centre at Rainbow Preschool Kalwa, Thane" },
    kasarvadavali: { src: "/images/centres/kasarvadavali.webp", alt: "Rainbow Preschool Kasarvadavali admission centre, Thane West" },
  },
  sections: {
    processIntro: "Joining Rainbow Preschool is straightforward. Here are the six steps from first enquiry to your child's first day.",
    ageIntro: "Each programme at Rainbow Preschool is designed for a specific developmental stage. Age is calculated as of June 1st of the academic year.",
    ageNote: "If your child's age falls between two programmes, our team will assess developmental readiness and guide you to the right fit.",
    documentsIntro: "Please keep the following documents ready to complete your child's admission at Rainbow Preschool.",
    documentsNote: "Our admissions team will guide you through the exact documentation needed for your chosen centre and programme.",
    timelineIntro: "Rainbow Preschool accepts applications year-round. Here is the typical admission calendar to help you plan.",
    centresIntro: "Choose the Rainbow Preschool centre that is most convenient for your home, commute, or daily routine. All 6 centres offer the same admissions programmes and quality standards.",
    faqIntro: "Common questions from parents enquiring about preschool admission in Thane",
    finalCtaTitle: "Ready to Start Your Child's Admission?",
    finalCtaDescription: "Call us, WhatsApp, or fill the form above — our admissions team responds within 24 hours.",
  },
  seoCopyBlock: {
    title: "Preschool Admissions Made Simple in Thane",
    para: "Rainbow Preschool International offers preschool admissions in Thane across Playgroup, Nursery, Jr. KG, and Sr. KG. Parents can explore age criteria, centre options, admission steps, and speak with our admissions team for personalised guidance across all six Thane locations. Whether you are applying for nursery admissions, kindergarten admissions, or looking to enrol your toddler in playgroup — our team will guide you through every step of the process.",
  },
} as const;