import { branches } from "./schema";

/**
 * Visitor-facing /contact copy, kept as plain shared data for browser and SSR
 * renderers. Branch names, addresses and contact numbers come from the
 * canonical centre records in shared/schema.
 */
export const CONTACT_PAGE_COPY = {
  h1: "Contact Us",
  intro: "Have questions about admissions or want to schedule a tour? We'd love to hear from you!",
  callbackHeading: "Request A Callback",
  callbackDescription: "Fill out the form and we'll get back to you shortly.",
  contactInformationHeading: "Contact Information",
  phoneLabel: "Phone",
  generalPhone: "82915 68972",
  emailLabel: "Email",
  email: "admin@rainbowpreschools.com",
  workingHoursLabel: "Working Hours",
  workingDays: "Monday - Saturday",
  workingHours: "9AM - 6PM",
  locationsLabel: "Locations",
  locationCount: "6 Centres across Thane West",
  nearestCentrePrompt: "Find your nearest centre below",
  quote: "The secret of getting ahead is getting started.",
  quoteAttribution: "— Mark Twain",
  centresHeading: "Our Centres",
  centresDescription: "Locate your nearest Rainbow Preschools Centre in Thane.",
  mapLabel: "Interactive map of Rainbow Preschool centres",
  mapLoading: "Loading the interactive centre map…",
  mapPlaceholder: "Map of 6 Rainbow Preschool centres across Thane. The interactive map loads as you approach; centre details are listed below.",
  map: {
    loading: "Loading 3D map…",
    accessibleDescription: "Interactive 3D map of 6 Rainbow Preschool centres across Thane. Use the cards below for keyboard access.",
    centreCount: "6 Centres · Thane",
    tapPinHint: "Tap pin · drag",
    clickPinHint: "Click pin · drag",
    closePopupPattern: "Close {name} popup",
    directions: "Directions",
    whatsapp: "WhatsApp",
    call: "Call",
    brand: "Rainbow Preschool",
    fallbackCentreCount: "6 Centres Across Thane",
    openMapsHint: "Click to open Maps",
    directionsPrompt: "Click on any location to open directions in Google Maps",
    openMapsForPattern: "{name} — open in Google Maps",
  },
  exploreHeading: "Explore Rainbow Preschool",
  links: [
    { href: "/play-school-near-me", label: "Award-Winning Preschool" },
    { href: "/play-school-near-me", label: "Find Nearest Centre" },
    { href: "/preschool-admissions", label: "Admission Process" },
    { href: "/gallery", label: "Photo Gallery" },
  ],
  branchCard: {
    view: "View",
    localCentre: "Centre",
    whatsapp: "WhatsApp",
    directions: "Directions",
  },
  branches,
  localPages: {
    aggarwal: { url: "/preschool-in-manpada-thane", locality: "Manpada" },
    hariniwas: { url: "/preschool-in-hariniwas-thane", locality: "Hariniwas" },
    "anand-nagar": { url: "/preschool-in-anand-nagar-thane", locality: "Anand Nagar" },
    dhokali: { url: "/preschool-in-dhokali-thane", locality: "Dhokali" },
    kalwa: { url: "/preschool-in-kalwa-thane", locality: "Kalwa" },
    kasarvadavali: { url: "/preschool-in-kasarvadavali-thane", locality: "Kasarvadavali" },
  },
  form: {
    parentName: "Parent Name *",
    parentNamePlaceholder: "Enter your name",
    phone: "Phone Number *",
    phonePlaceholder: "Enter phone number",
    emailLabel: "Email",
    emailPlaceholder: "Enter email address",
    childName: "Child's Name *",
    childNamePlaceholder: "Enter child's name",
    childAge: "Child's Age *",
    agePlaceholder: "Select age",
    ages: ["Below 1.5 years", "1.5 - 2 years", "2 - 2.5 years", "2.5 - 3 years", "3 - 3.5 years", "3.5 - 4 years", "4 - 5 years", "5 - 6 years", "Above 6 years"],
    programme: "Programme *",
    programmePlaceholder: "Select programme",
    preferredCentre: "Preferred Centre *",
    centrePlaceholder: "Select centre",
    message: "Message (Optional)",
    messagePlaceholder: "Any questions or specific requirements?",
    submit: "Request Callback",
    submitting: "Submitting...",
    thankYou: "Thank You!",
    received: "We've received your request and will contact you within 24 hours.",
    submitAnother: "Submit Another Request",
    submittedToast: "Request Submitted!",
    submittedDescription: "We'll get back to you within 24 hours.",
    errorToast: "Something went wrong",
    errorDescription: "Please try again or call us directly.",
  },
} as const;