/** Text-only source of truth for the /playgroup visitor and crawler pages. */
export const PLAYGROUP_COPY = {
  title: "Playgroup in Thane for 1.5–2.5 Years | Rainbow Preschool",
  description: "Playgroup for toddlers aged 1.5 to 2.5 years at our 6 Rainbow Preschool International centres in Thane. Morning and afternoon batches, play-based learning.",
  h1: "Playgroup in Thane for Children Aged 1.5 to 2.5 Years",
  publishDate: "2026-09-30",
  publishDateDisplay: "September 30, 2026",
  heroBadge: "Ages 1.5 - 2.5 Years",
  heroSubline: "A joyful, safe first step into learning, routine and friendships for toddlers in Thane.",
  whyHeading: "Why Playgroup Matters Between 1.5 and 2.5 Years",
  whyParagraphs: [
    "Playgroup is your child's first structured learning experience outside home. Between 1.5 and 2.5 years, toddlers learn fastest through play, so our playgroup gives them a gentle, happy introduction to routine, friends and new skills.",
    "At Rainbow Preschool, our playgroup focuses on social interaction, sensory exploration and motor skills. Through planned activities, children learn to share, take turns and build confidence in a safe, caring space.",
  ],
  whyFinalSegments: [
    { text: "Early, well-guided play supports language, thinking and emotional development, and gives your child a strong foundation for " },
    { text: "nursery", href: "/nursery" },
    { text: "." },
  ],
  dayHeading: "A Typical Day in Our Playgroup",
  dayIntro: "Our morning batch runs from 8:30 to 11:30 AM, Monday to Friday. The afternoon batch, 12:30 to 3:30 PM, follows the same gentle rhythm.",
  routine: [
    { time: "8:30 AM", activity: "Welcome Circle & Attendance", description: "Warm greetings and settling in" },
    { time: "9:00 AM", activity: "Free Play & Exploration", description: "Open-ended play with toys and materials" },
    { time: "9:30 AM", activity: "Rhymes & Songs", description: "Music, movement, and language development" },
    { time: "10:00 AM", activity: "Snack Time", description: "Healthy snacks and social interaction" },
    { time: "10:30 AM", activity: "Learning Activity", description: "Colors, shapes, or sensory exploration" },
    { time: "11:00 AM", activity: "Outdoor Play", description: "Physical activity and motor skill development" },
    { time: "11:30 AM", activity: "Story Time & Goodbye", description: "Calming stories and preparation for pickup" },
  ],
  learningHeading: "What Your Child Will Learn",
  learningIntro: "Our playgroup curriculum nurtures every side of your toddler's development through play.",
  learningTags: ["Colors & Shapes", "Sensory Play", "Motor Skills", "Language through Songs", "Social Interaction", "Storytelling"],
  enquiryHeading: "Want to Know If Playgroup Is Right for Your Child?",
  enquiryIntro: "Our admission experts are here to guide you. Share your details and we'll help you understand how our playgroup can benefit your child.",
  enquiryBullets: [
    "Personalized guidance for your child's needs",
    "Schedule a centre visit at your convenience",
    "Ask about fees and the admission process",
  ],
  chooseHeading: "Why Choose Our Playgroup?",
  chooseBullets: [
    "30:2 student–teacher ratio for individual attention",
    "ECCE-trained, caring female teachers",
    "Safe and hygienic environment",
    "Gentle transition to school routine",
    "Structured yet flexible curriculum",
  ],
  timings: ["Morning Batch – 8:30 AM to 11:30 AM", "Afternoon Batch – 12:30 PM to 3:30 PM", "Monday to Friday"],
  localityHeading: "Playgroup in Thane: Why Families Choose Rainbow",
  localityIntro: "Looking for a trusted playgroup in Thane? Rainbow Preschool International has cared for Thane's youngest learners since 2007, with over 1 lakh children taught across our 6 centres.",
  nearHeading: "A playgroup near you in Thane",
  centreAreas: "Manpada, Hariniwas (Panchpakhadi), Anand Nagar, Dhokali, Kalwa and Kasarvadavali",
  nearText: "Our centres are in Manpada, Hariniwas (Panchpakhadi), Anand Nagar, Dhokali, Kalwa and Kasarvadavali, easy to reach from Ghodbunder Road, LBS Marg, Pokhran Road and the Eastern Express Highway.",
  checklistHeading: "What makes our Thane playgroup different",
  checklist: [
    { emphasis: "30:2 student–teacher ratio", rest: ": your child is noticed every day" },
    { emphasis: "100% female teaching staff", rest: " with ECCE training" },
    { emphasis: "CCTV-monitored classrooms", rest: " at all 6 centres" },
    { emphasis: "Play-based curriculum", rest: " aligned with NEP 2020" },
    { emphasis: "Daily parent updates", rest: " and monthly progress reports" },
  ],
  newToPlaygroupSegments: [
    { text: "Take our 2-minute readiness quiz to see whether your toddler is ready, or read our guides on the " },
    { text: "right age to start play school", href: "/blog/what-age-start-play-school" },
    { text: ", the " },
    { text: "benefits of play school for two-year-olds", href: "/blog/benefits-play-school-2-year-olds" },
    { text: ", and " },
    { text: "preparing for the first day", href: "/blog/preparing-your-child-for-first-day-preschool" },
    { text: "." },
  ],
  galleryHeading: "Glimpses of Our Playgroup",
  galleryIntro: "See our toddlers exploring, playing, and learning in our safe and colorful classrooms.",
  safetyHeading: "Our Safety & Hygiene Promise",
  safetyIntro: "Your child's safety is our top priority. Here's how we ensure a secure environment.",
  safetyCards: [
    { title: "Regular Sanitization", text: "All toys, surfaces, and classrooms sanitized multiple times daily" },
    { title: "100% Female Staff", text: "All caregivers and teachers are trained female professionals" },
    { title: "CCTV Surveillance", text: "Monitoring across key campus areas" },
    { title: "Parent Communication", text: "Regular updates on your child's activities and progress" },
  ],
  activitiesHeading: "Daily Activities",
  activitiesIntro: "A variety of engaging activities to keep your child learning and having fun.",
  activities: ["Circle time", "Music & movement", "Art exploration", "Free play", "Outdoor activities", "Rhymes & songs", "Sensory play", "Puppet shows"],
  highlightsHeading: "Programme Highlights",
  highlights: [
    "Individual attention with a 30:2 student–teacher ratio",
    "ECCE-trained, experienced teachers",
    "Safe and secure environment",
    "Regular parent updates and communication",
  ],
  centresHeading: "Playgroup Centres in Thane",
  centresIntro: "Find a Rainbow Preschool playgroup near you. We have 6 centres across Thane.",
  faqHeading: "Playgroup FAQs",
  faqIntro: "Common questions parents ask about our playgroup programme.",
  exploreHeading: "Explore Rainbow Preschool",
  exploreLabels: ["Kindergarten Programme", "Find Nearest Centre", "Admission Process", "Nursery Programme"],
  finalHeading: "Ready to Begin Your Child's Happy Learning Journey?",
  finalIntro: "Give your toddler a happy, confident start with our playgroup.",
} as const;

export const PLAYGROUP_WEBPAGE_SCHEMA = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  "@id": "https://www.rainbowpreschools.com/playgroup#webpage",
  url: "https://www.rainbowpreschools.com/playgroup",
  name: PLAYGROUP_COPY.h1,
  description: PLAYGROUP_COPY.description,
  dateModified: PLAYGROUP_COPY.publishDate,
  publisher: { "@id": "https://www.rainbowpreschools.com/#organization" },
  about: { "@id": "https://www.rainbowpreschools.com/#organization" },
};