import { PLAY_SCHOOL_NEAR_ME_CONTENT } from "./play-school-near-me-content";

export { PLAY_SCHOOL_NEAR_ME_CONTENT };
export const PLAY_SCHOOL_NEAR_ME_H1 = PLAY_SCHOOL_NEAR_ME_CONTENT.h1;
export const PLAY_SCHOOL_NEAR_ME_INTRO = PLAY_SCHOOL_NEAR_ME_CONTENT.intro;